### ISSUE TITLE
[Docs] Add OSM adapter to meshery.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#1]
**Desired State:**
Open Service Mesh adapter should be listed as an alpha status adapter on https://meshery.io

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@Anita-ihuman @Adeola-Adesoba @PluckyPrecious any takers?

**Comment by manishdangi98** [comment]
@leecalcote can I take this

**Comment by leecalcote** [comment]
thanks, @manishdangi98. It couldn't wait any longer, so I just implemented a few moments ago - https://github.com/layer5io/meshery.io/pull/285

There are two other very similar issues open on this, though. Please grab them (self-assign). 👍 

- https://github.com/layer5io/layer5/issues/595 - - this one is open.
- https://github.com/layer5io/meshery/issues/1375 - - actually, @PluckyPrecious has this one.

**Comment by leecalcote** [comment]
Thank you, all.
