### ISSUE TITLE
Add releasedrafter workflow and configuration files to this repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#16]
**Current Situation**
The [ReleaseDrafter](https://github.com/marketplace/actions/release-drafter) utility (GitHub Action) is not configured in this repository.

**Desired Situation**
- Releasedrafter should be configured to execute whenever a PR is merged to master in this repo.

**Implementation**
- Copy the [releasedrafter config](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml) and the [releasedrafter workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml) file from the `meshery` repo and place in the `.github` folder here.

**Comment by chandrashritii** [comment]
@Neilblaze Do you wanna take this up?

**Comment by Neilblaze** [comment]
@chandrashritii Sure, I've created a PR regarding that :rocket:
