### ISSUE TITLE
Add Release Drafter for the repository

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/meshery-osm#24]
**Current Situation**
Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Situation**
Add ReleaseDrafter configuration yaml file & GitHub Action.

---

 **Additional context**
[Release drafter configuration file](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[Rlease drafter Github action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

**Comment by PluckyPrecious** [comment]
A PR was merged to this effect 9days ago, so I’ll close now.
