### ISSUE TITLE
unable to create kubeconfig: open /root/.kube/config

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#27]
**Description**
Beta version of this adapter is released in Meshery v0.4.2 is reporting:

```
meshery-osm_1       | time="2020-08-17T04:12:10Z" level=error msg="unable to create kubeconfig: open /root/.kube/config: no such file or directory"
```

**Enviroment:**
 - OS: MacOS
 - Browser: Safari
 - running Docker Desktop

**Comment by leecalcote** [comment]
@kumarabd, is this an "out of cluster" issue only?

**Comment by kumarabd** [comment]
@leecalcote  this issue slipped out of notice. This shouldn't ideally happen, let me look into this.
