### ISSUE TITLE
[Chore] Issue Templates need updated to reference the correct label names

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#4]
**Description**
The [issue templates in this repo](https://github.com/layer5io/meshery-osm/tree/master/.github/ISSUE_TEMPLATE) incorrectly reference labels like `bug` and `enhancement`.

**Expected Behavior**
These issue templates should be updated to reference the new label names like `kind/bug` and `kind/enhancement`

**Comment by chandrashritii** [comment]
@crustyy Would you like to take this one?

**Comment by edwvilla** [comment]
can i take this?
