### ISSUE TITLE
Add pull-request template for the repository

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery-osm#46]
**Current State:**

There is no PR template and contributor has to manually populate the details

**Desired State:**

Add pull-request template for the repository

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by kushthedude** [comment]
Pull request template to be used https://github.com/layer5io/meshery/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by thescripted** [comment]
Hey if you don't mind, I'd be happy to implement this!

**Comment by kushthedude** [comment]
Hey @thescripted, Please go ahead 😄 !
