### ISSUE TITLE
[Chore] Update issue templates

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery-osm#5]
**Current Behavior**

Currently, the [issue templates](https://github.com/layer5io/meshery-osm/tree/master/.github/ISSUE_TEMPLATE) only consist of a basic structure. 

**Desired Behavior**

Update the templates to reflect the proper guidelines. Refer: [Layer5 Issue templates.](https://github.com/layer5io/layer5/tree/master/.github/ISSUE_TEMPLATE)

**Comment by edwvilla** [comment]
Already updated the labels, so i might aswell take this

**Comment by chandrashritii** [comment]
@edwvilla Thanks. Go ahead

**Comment by edwvilla** [comment]
Comparing both repos, the only difference that i consider needs to be added here is the chore template

there are some cases that refers `contributor resources` for that particular repo, does that part needs to be added here?

**Comment by leecalcote** [comment]
> Comparing both repos, the only difference that i consider needs to be added here is the chore template
> 
> there are some cases that refers `contributor resources` for that particular repo, does that part needs to be added here?

Contributor resources for a Docs issue might be the only issue type that needs contributor resources defined.

**Comment by leecalcote** [comment]
The issue templates to be copied should be from https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE

**Comment by edwvilla** [comment]
Seems like those templates have been added already, same as the Contributor resources part on the doc template

**Comment by leecalcote** [comment]
@edwvilla very good! Thank you for this. We're good to close out here. 👍
