### ISSUE TITLE
[SMI] Adapter crashes on run of SMI Conformance test

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#57]
**Description**
<img width="1310" alt="Screen Shot 2020-10-07 at 11 00 52 PM" src="https://user-images.githubusercontent.com/7570704/95413490-34beeb80-08f1-11eb-80f7-e2171717c395.png">

**Comment by leecalcote** [comment]
@dhruv0000 fyi

**Comment by Nikhil-Ladha** [comment]
A similar issue is created on the meshery repo too and I think @kumarabd is working on it already.
It's some issue with the OSM docker image being missing.

**Comment by kumarabd** [comment]
Should be good first issue for @dhruv0000  to work on. I've already created and assigned the PR in osm-adapter to @dhruv0000 .

**Comment by dhruv0000** [comment]
The snackbar is different issue, relating to the meshery provider database endpoint not being found, which is discussed in [#1631](https://github.com/layer5io/meshery/issues/1631).

This issue discussed here is the adapter crash with panic while invoking a SMI test using OSM adapter.
![osm_smi_test_srgfault](https://user-images.githubusercontent.com/44001539/95501805-7ff6fe00-09c6-11eb-9208-6b3a513b135c.png)

**Comment by kumarabd** [comment]
Thanks @dhruv0000 . This looks like an issue when logged in, @Nikhil-Ladha  does it occur when u login without a provider?

**Comment by Nikhil-Ladha** [comment]
Will have to check that...I will update my findings here after doing the check.
