### ISSUE TITLE
Replace meshery-osm adapter to use meshey-kit and meshery-framework as primary dependencies

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-osm#65]
**Enhancement Description**
A brief description of the enhancement.

As we discussed we should replace `meshery-osm` adapter to use `meshey-kit `and `meshery-framework` as primary dependencies. So I'm going to work on `meshery-osm` adapter @kumarabd @leecalcote @mgfeller 

**Related Challenges**
A brief description of what the problem is. (e.g. I need to be able to...)

---
[Optional] **Alternatives**
A brief description of any alternative solutions or features you've considered.

[Optional] **Additional context**

**Comment by leecalcote** [comment]
This sounds. Wonderful.

**Comment by mgfeller** [comment]
This is great!

**Comment by Aisuko** [comment]
Thank you guys
