### ISSUE TITLE
[Sample App] Support OSM Book Buyer App

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-osm#69]
**Enhancement Description**
Like other service meshes, Open Service Mesh has a sample application used to demonstrate its functionality.

The Meshery Adapter for OSM should support the project's sample application, Book Buyer: https://github.com/openservicemesh/osm/tree/main/demo

**Comment by ishankhare07** [comment]
Hey @leecalcote looking into this, I wanted to understand the functionality around adapter templates.
Where can I get some documentation around it, if any?

**Comment by leecalcote** [comment]
@mgfeller have we put much around this in the Meshery Adapters doc?

**Comment by mgfeller** [comment]
> @mgfeller have we put much around this in the Meshery Adapters doc?

No, I don't think so, but I'm not quite sure whether "templates" here refers to https://github.com/layer5io/meshery-adapter-template or something else.. @ishankhare07 ?
