### ISSUE TITLE
[Chore] Add community guidelines

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/meshery-osm#7]
**Current Behavior**
Community guidelines, including the contributing guide and the code of conduct is missing.

**Desired Behavior**
Migrate the [contributing guide](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/layer5io/layer5/blob/master/CODE_OF_CONDUCT.md) from the Layer5 repository.

**Comment by emmanuellar** [comment]
I'd love to take this up. Came across this from the first-timers-only twitter handle and it's my first time contributing to open source.

**Comment by leecalcote** [comment]
Excellent, @emmanuellar. We would love to be your first. 😄

**Comment by leecalcote** [comment]
@emmanuellar as you go through this process, you're most welcome to ask questions here. Also, know that if your questions are involved or if you enjoyed this first issue and would like to engage in more, you're welcome to join the Layer5 open source community here - http://slack.layer5.io. There's a collection of first-time and seasoned contributors who are all learning together in this community.

**Comment by emmanuellar** [comment]
Thank you so much for the chance and for replying so quick, wow! I'll go ahead and clone the project.
